/*    
 Copyright 2015 Adobe Systems Incorporated.  All rights reserved. 
    Purpose- This file contains all the Constants that are used in New Document Dialog Browser View
*/
/*jslint vars: true, plusplus: true, devel: true, browser: true, nomen: true, maxerr: 50 */
/*jshint -W100 */

var DW_NDD_CONSTANTS = {
    BrowserMainURL: "/NDD/browsercontent/NDD_Browser_UI_Main.html",
    BrowserUIHtmlUrl: "NDD_Browser_UI_HTML.html",
    StringsFilePath: "/NDD/strings/",
    BootstrapFile: "bootstrap.css",
    BootstrapJS: "/js/bootstrap.js",
    Bootstrap3File: "bootstrap-3.3.7.css",
	Bootstrap3JS: "/js/bootstrap-3.3.7.js",
    Bootstrap4File: "bootstrap-4.0.0.css",
    Bootstrap4JS: "/js/bootstrap-4.0.0.js",
	JQueryMinJS: "/js/jquery-1.11.3.min.js",
    PopperMinJS: "/js/popper.min.js",
	BootstrapCreationInProgress: 1,
	AllValidationDone: 2,
	StopOnOKHandling: 3,
	LayoutTypeNone: "none",
	LayoutTypeBootstrap: "bootstrap",
	UseExistingBootstrap: "useexisting",
	BuildNewBootstrap: "buildnew",
    BootstrapCss: "/css/bootstrap.css",
	Bootstrap3Css: "/css/bootstrap-3.3.7.css",
    Bootstrap4Css: "/css/bootstrap-4.0.0.css",
    Bootstrap3Bundle: "Shared/LiveEdit/ResponsiveAssets/bootstrap3/bundle",
    Bootstrap4Bundle: "Shared/LiveEdit/ResponsiveAssets/bootstrap4/bundle",
    DocTypeDefault: 2,
	ScreenSmDefault: 768,
	ScreenMdDefault: 992,
	ScreenLgDefault: 1200,
    ScreenSmDefault4: 576,
    ScreenMdDefault4: 768,
    ScreenLgDefault4: 992,
    ScreenXLgDefault4: 1200,
	NumberOfColDefault: 12,
	GutterWidthDefault: 30,
	FILTER: "BootstrapCSS (bootstrap*.css",
    FILTER_MAC: "*.css",
    BootstrapHelpUrl: "http://getbootstrap.com",
	BootstrapKBArticleUrl: "https://www.adobe.com/go/nddbs",
    NumberOfColMin: 1,
    NumberOfColMax: 24,
    GutterWidthMin: 1,
    GutterWidthMax: 120,
    //max len of characters in css filename that can be shown in attach css list box
    AttachCssMaxLenWin: 28,
    AttachCssMaxLenMac: 30,
    TabKeyCode: 9,
    SpacebarKeyCode: 32,
    FontForWindows: "Tahoma",
    OveriteSiteBootstrap: "Overwrite_site_bootstrap",
    BootstrapDoesNotExist: "Bootstrap_does_not_exist",
    BootstrapNotInSite: "Bootstrap_not_in_site"
};

var UI_HTML_CONSTANTS = {
    titleId : "title",
    dtdId : "dtd",
    attachCssAddId : "attachCssAdd",
    attachCssRemoveId : "attachCssRemove",
    attachCssListId : "attachCssList",
    frameworkContentId : "frameworkContent",
    htmlNoneTabId : "tabHeader_1",
    bootStrapTabId : "tabHeader_2",
    htmlNoneContentId : "htmlNoneContent",
    bootstrapContentId : "bootstrapContent",
    bootstrapHelpLink : "bootstrapHelpLink",
	generateBootstrap: "generateBootstrap",
	existingBootstrap: "existingBootstrap",
    useExistingBox: "useExistingBox",
	bootstrapPath: "bootstrapPath",
    attachCssAddBootstrap : "attachCssAddBootstrap",
    attachCssRemoveBootstrap : "attachCssRemoveBootstrap",
    attachCssListBootstrap : "attachCssListBootstrap",
	noOfColumn: "noOfColumn",
	gutterWidth: "gutterWidth",
	screenSmall: "screenSmall",
	screenMedium: "screenMedium",
    screenLarge: "screenLarge",
    screenExtraLarge: "screenExtraLarge",
    screenExtraExtraLarge: "screenExtraExtraLarge",
	xlScreenLinked1: "xlScreenLinked1",
    xlScreenLinked2: "xlScreenLinked2",
	prebuiltLayout: "prebuiltLayout",
	dwBootCSSSrcBtn: "dwBootCSSSrcBtn",
    advanceSettingsContent : "advanceSettings",
    showAdvanceSettingsText : "showAdvanceSettingsText",
    customizeText : "customizeText",
    customizeTextDesc : "customizeTextDesc",
    detailFrameId : "detailFrame",
    xlScreen : "xlScreen",
    xxlScreen : "xxlScreen"
};

var LABEL_CONSTANTS = {
    bootstrapTabLabel : "bootstrapTabLabel",
    bootstrapErrorLabel : "bootstrapErrorLabel",
    titleLabel : "titleLabel",
    docTypeLabel : "docTypeLabel",
    attachCssNoneLabel : "attachCssNoneLabel",
    bootstrapCssLabel : "bootstrapCssLabel",
    createNewLabel : "createNewLabel",
    useExistingLabel : "useExistingLabel",
    attachCssBSLabel : "attachCssBSLabel",
    deisgnLabel : "deisgnLabel",
    prebuiltLayoutLabel : "prebuiltLayoutLabel",
    customizeDescLabel : "customizeDescLabel",
    columnLabel : "columnLabel",
    gutterLabel : "gutterLabel",
    screenLabel : "screenLabel",
    gridLabel : "gridLabel",
    smallLabel : "smallLabel",
    mediumLabel : "mediumLabel",
    largeLabel : "largeLabel",
    extraLargeLabel : "extraLargeLabel",
    extraExtraLargeLabel : "extraExtraLargeLabel"
};

var LOGGING_CONSTANTS = {
    NDD_Layout: "NDD Layout",
    Bootstrap_NDD_CustomizeFailed: "Bootstrap_NDD_CustomizeFailed"
};
